import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section
        id="hero"
        className="pt-10 pb-10 relative min-h-screen-without-nav items-center content-center flex bg-primary-100 dark:bg-gray-900"
      >
        <div className="flex items-center justify-between w-full relative max-w-2xl border-gray-200 dark:border-gray-700 mx-auto pt-4 pb-4 sm:pb-4  text-gray-900  dark:bg-gray-900 dark:text-gray-100">
          <div className="container gap-8 md:gap-0 mx-6 sm:mx-auto grid md:grid-cols-2 items-center content-center justify-items-center">
            <h1 className="text-4xl font-bold md:text-6xl flex flex-col items-center md:items-start">
              <span>Malika is a</span>
              <span className="animate-title-part1" href="#portfolio">
                software developer
              </span>
              <span className="animate-title-part2" href="#stats">
                foodie
              </span>
              <span className="animate-title-part3" href="#personal">
                travel lover
              </span>
            </h1>
            <div className="w-3/4"></div>
          </div>
        </div>
      </section>
      <section
        id="hero"
        className="pt-10 pb-10 relative min-h-screen-without-nav items-center content-center flex bg-white-100"
      >
        <div className="flex items-center justify-between w-full relative max-w-2xl border-gray-200 dark:border-gray-700 mx-auto pt-4 pb-4 sm:pb-4  text-gray-900  dark:bg-gray-900 dark:text-gray-100">
          <div className="container gap-8 md:gap-0 mx-6 sm:mx-auto grid md:grid-cols-2 items-center content-center justify-items-center">
            <h1 className="text-4xl font-bold md:text-6xl flex flex-col items-center md:items-start">
              <span>Malika is a</span>
              <span className="animate-title-part1" href="#portfolio">
                software developer
              </span>
              <span className="animate-title-part2" href="#stats">
                foodie
              </span>
              <span className="animate-title-part3" href="#personal">
                travel lover
              </span>
            </h1>
            <div className="w-3/4"></div>
          </div>
        </div>
      </section>
      <section
        id="hero"
        className="pt-10 pb-10 relative min-h-screen-without-nav items-center content-center flex bg-primary-100 dark:bg-gray-900"
      >
        <div className="flex items-center justify-between w-full relative max-w-2xl border-gray-200 dark:border-gray-700 mx-auto pt-4 pb-4 sm:pb-4  text-gray-900  dark:bg-gray-900 dark:text-gray-100">
          <div className="container gap-8 md:gap-0 mx-6 sm:mx-auto grid md:grid-cols-2 items-center content-center justify-items-center">
            <h1 className="text-4xl font-bold md:text-6xl flex flex-col items-center md:items-start">
              <span>Malika is a</span>
              <span className="animate-title-part1" href="#portfolio">
                software developer
              </span>
              <span className="animate-title-part2" href="#stats">
                foodie
              </span>
              <span className="animate-title-part3" href="#personal">
                travel lover
              </span>
            </h1>
            <div className="w-3/4"></div>
          </div>
        </div>
      </section>
      <section
        id="portfolio"
        // ref={portfolioRef}
        className="dark:bg-lightgrey text-text"
      >
        <div className="container mx-auto min-h-screen-without-nav items-center content-center py-12">
          <h2 className="text-center text-2xl mb-6 md:mb-12 font-bold">
            Some of my work
          </h2>
          {/* <Portfolio /> */}
        </div>
      </section>
      <section
        id="blog"
        // ref={blogRef}
        className="bg-purple dark:bg-darkgrey text-text"
      >
        <div className="container mx-auto min-h-screen-without-nav flex flex-col items-center justify-center py-12">
          <h2 className="text-center text-2xl mb-6 md:mb-12 font-bold">
            Personal blog - most read
          </h2>
          {/* <Blog blogs={blogs} /> */}
        </div>
      </section>
      <section
        // ref={statsRef}
        id="stats"
        className="dark:bg-lightgrey text-text"
      >
        <div className="container mx-auto min-h-screen-without-nav flex flex-col items-center justify-center py-12 w-full">
          <h2 className="text-center text-2xl mb-6 md:mb-12 font-bold">
            My Strava stats
          </h2>
          {/* <StravaStats
            stravaStats={stravaStats}
            stravaMostRecentRun={stravaMostRecentRun}
            stravaMostRecentRide={stravaMostRecentRide}
          /> */}
        </div>
      </section>
      <section
        id="contact"
        // ref={contactRef}
        className="bg-purple dark:bg-darkgrey text-text"
      >
        <div className="container grid md:grid-cols-2 gap-6 min-h-screen-without-nav content-center align-items"></div>
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
